### ISSUE TITLE
Julia language interoperability (meta-issue)

### ISSUE THREAD

**Issue by stevengj** [ipython/ipython#3806]
As suggested by @fperez, this is a meta-issue to collect obstacles that we ran into in working on a native [Julia kernel](https://github.com/JuliaLang/julia-ipython) for IPython.  (Many of these were found, fixed, or worked around during the IPython developer's workshop last week.)
- [x] The wire protocol was misdocumented; fixed in #3756
- [x] serialization protocol (JSON) of dictionaries wasn't clear in doc (mostly fixed as of #3756)
- [x] `payload` of `execute_reply` is unclear
- [x] `source` of `display_data` is unclear (am told this is somewhat arbitrary and we can just use `"julia"`).  ( ~~Apparently it can just be omitted without causing any obvious problems, but not sure if this is kosher?~~ Correction: must be included for qtconsole.)
- [ ] `metadata` of `display_data` is poorly documented (and apparently can be omitted without causing problems, but not sure if this is kosher?).  According to @fperez it is only used right now to specify image width/height as a way of rescaling large images, but we feel like this is a clumsy way to do this.  (A global preference in the front-end to set a maximum image-display size, with an interface to click to see the whole image, might be more appropriate for that task).
- [ ] The whole `heartbeat` thing is unclear. Apparently, it is just a `REP` socket that echoes all messages back to itself, and needs to be implemented in a separate OS thread or process in order to stay responsive even if the kernel is busy.
- [x] We had several problems with overly aggressive timeouts in some front-ends (currently the Julia kernel takes a couple of seconds to launch, and IPython thought we died), but I think these have been mostly fixed? @StefanKarpinski?
- [ ] Apparently the `pyout` response must be sent before `execute_reply` or the `Out[xx]` may be displayed out-of-order in the console?  This is a little bit concerning because they are on different zeromq sockets and I'm not sure zeromq guarantees the order in which they arrive.
- [ ] For `pyerr` messages, IPython seems to ignore the `ename` and `evalue` fields, and expects the error message to be the first element of the `traceback` list, contrary to docs.
- [ ] The `crash` message type is apparently unimplemented in the IPython front-end (and should have been in "future ideas"?)  Might be nice to have this, as a way of indicating what went wrong if we catch an unexpected exception in the kernel and abort, although obviously not all kinds of crashes will be nice enough to allow graceful error reporting.
- [ ] `object_info_reply` is currently quite Python-centric.  For example, it would be nice if `argspec` were a list so that we could return all the methods for a given function.
- [x] The content of `object_info_request` and `reply` uses `oname`, not `name`. (I think was fixed in #3756.)
- [ ] The documentation says that `execute_request` has a boolean field `store_history`, but this is absent from what the notebook sends.  It seems like we are just supposed to infer this from `silent`.
- [ ] Would be much easier to test things if an explicit example could be given, for each message type, of how to trigger that request from the `notebook` front-end.  (Better yet, from the `console` front-end, since that is easier to get going when you are first starting on kernel development).  For example, I'm still not sure how to get the notebook to send me a `history_request` (although qtconsole sends this on startup).
- [ ] `history_reply` is unclear to me, and qtconsole seems to differ from the spec in several ways.  Is the `line_number` the same as the current execution counter?  What is the difference between "raw" and "transformed" input?  Does "pattern" search the input (raw or transformed?) or output?  What does "content" mean when it says "tuples" (which are not a JSON type) ... is this just a JSON list?  Are the "input" and "output" parameters dictionaries, lists, ...?  In what format is the "output" sent (text output, a dictionary of MIME=>data, or ...?)?  Does "duplicated" history refer to duplicated input or output?   Is the glob pattern treated like some kind of shell globbing (or is it a PCRE)?  qtconsole's `history_request` seems to omit many of the specified `content` fields (it only sends `output`, `hist_access_type`, `raw`, and `n`); what are the defaults for the omitted fields?  What should we use for "session" (which is omitted from the qtconsole `history_request`, contrary to spec)? 
- [ ] `pyout` messages need an undocumented `metadata` dictionary field in order to work with `qtconsole`.
- [ ] `qtconsole` uses Python-centric rules to decide whether the input has ended or not, which don't always work in other languages.  There probably needs to be a new message type to request this information from the back end.  (see JuliaLang/IJulia.jl#22).
- [ ] Documentation tooltips don't work for non-Pythonic identifiers.  e.g. typing `push(` and hitting TAB in the notebook front-end sends an `object_info_request` and uses the result to display a tooltip, but the same thing does nothing for `push!(` since `push!` is a valid identifier in Julia but not in Python.  (Note that this should be fixed by the new `inspect_request` in the 5.0 protocol, which sends the entire code cell and lets the kernel decide what object is being queried.)

cc: @JeffBezanson, @StefanKarpinski, @minrk

**Comment by lilinjn** [comment]
Hi -- I experience the two following issues:

++ When rendering julia notebooks which use unicode in identifiers, while the notebook is running things are fine, but when the notebook is rendered to static html (either via command line or via nbviewer), there are annoying red boxes around the characters.   For an example, see http://nbviewer.ipython.org/github/lilinjn/lilKanren/blob/master/FirstSteps.ipynb (scroll down a bit)

++ When attempting to render a julia notebook to MD via `ipython nbconvert --profile julia --to markdown FirstSteps.ipynb`, stuff is not being put into code blocks, it just comes out as raw text

I'm motivated enough attempt a fix myself -- but if anyone has suggestions about what code base to consider, which community to talk to (python, julia, ijulia)  to make any upstream merges more likely, that would be great.

**Comment by Carreau** [comment]
> [red boxes]

Pygments highlighter need to be updated (http://pygments.org/demo/1061745/) 

> + When attempting to render a julia notebook to MD via ipython nbconvert --profile julia --to markdown FirstSteps.ipynb, stuff is not being put into code blocks, it just comes out as raw text

try https://github.com/ipython/ipython/blob/master/IPython/nbconvert/templates/markdown.tpl#L10-L12

the indented 4 spaces shoud make code block, but we can change to triple backticks. DO you want to give a shot at it ?

**Comment by lilinjn** [comment]
Hi -- I spaced out while looking at the MD in my text editor and forgot about the 4 space convention -- my vote would be to actually just leave it as it -- the indented style is simpler -- apologies

thanks for the pointer to pygments.

**Comment by Carreau** [comment]
@ellisonbg did you close because all point were addressed? or just because of last comment ?

> Hi -- I spaced out while looking at the MD in my text editor and forgot about the 4 space convention -- my vote would be to actually just leave it as it -- the indented style is simpler -- apologies

No problem. 

The backtick mode might make sens to, if we use it with language identifier to get highlighting.

**Comment by lilinjn** [comment]
Yup -- also the generated, but indented, MD renders as one big code block rather than distinct snippets, making it hard to distinguish inputs from outputs, so perhaps I change my mind again.  I'll try sending in a pull request in a few days.  cheers

**Comment by ellisonbg** [comment]
Hmm, I think I closed this by mistake. Sorry...
